### ISSUE TITLE
making it a variant

### ISSUE THREAD

**Issue by pasupulaphani** [rockabox/ng-lodash#13]
Hi Cabrel,

Thanks for the effort in putting library to make it easy to use in Angular.

Lodash is continuously improving, we upgrade when required.

This library should be a variant to lodash. It should be able to provide reference to user installed lodash not to the version this has copied.

I just wanted to state my opinion. Hope you will understand.
Kind regards,
Phani.

**Comment by dan-silva** [comment]
I agree. At this exact moment, I'm having a problem that could be solved with lodash version 3.1.0, but I'm not able to upgrade it indenpendently from this module.

**Comment by pasupulaphani** [comment]
Hi @dan-silva , Here are some examples that might help you. 

http://blog.mohammedlakkadshaw.com/AngularJS_Underscore_ultimate_web_development.html#.VNezU1RtN5Q

http://www.bennadel.com/blog/2720-creating-and-extending-a-lodash-underscore-service-in-angularjs.htm

Kind regards,
Phani.

**Comment by nwhite89** [comment]
Hi @pasupulaphani and @dan-silva the reason that ``ng-lodash`` won't allow you to use any version of lo-dash is that it the idea is that wraps lodash using ``lodash-cli`` as it's own Angular module rather than putting Lo-Dash on the window scope. You can look at updating ``ng-lodash`` to use ``v3.1`` of Lo-Dash and re-building and we can look at using that as a release instead.

**Comment by pasupulaphani** [comment]
Hi @nwhite89 ,

Yes that was a problem where it binds to window._ scope.

They also come with _.noConflict(). I don't see much use to wrap.

I'm quite interested in updating this library to make it more useful to users. I'm not seeing the necessity to wrap it. Is there something I'm missing.

Kind regrads,
Phani.

**Comment by nwhite89** [comment]
The point of wrapping is to enforce the normal Angular standard rather than doing a make shift way, this also allows for serving across multiple sites and never needing to mess with another site's window scope. For the needs of this project it is necessary to wrap I am afraid.

**Comment by nwhite89** [comment]
I'm closing this issue as I am afraid this isn't viable for this project.

**Comment by pasupulaphani** [comment]
No worries Nick. Thank you for your time and info.

**Comment by nwhite89** [comment]
No problem, there us a PR to use the latest version of loads https://github.com/rockabox/ng-lodash/pull/15 if that helps you.
