### ISSUE TITLE
Integrate current lodash master version

### ISSUE THREAD

**Issue by linslin** [rockabox/ng-lodash#14]
Could you update this library to depend on the current release version of lodash? https://github.com/lodash/lodash/releases/tag/3.0.0. Many thanks.

**Comment by egel** [comment]
+1

**Comment by nwhite89** [comment]
This has started to be looked at within this pr thanks to @jgermade
https://github.com/rockabox/ng-lodash/pull/15

**Comment by linslin** [comment]
:+1:

**Comment by nwhite89** [comment]
Closing since #15 merged and released https://github.com/rockabox/ng-lodash/releases/tag/0.2.0
