### ISSUE TITLE
Remove the angular dependency

### ISSUE THREAD

**Issue by varmint09** [rockabox/ng-lodash#16]
I don't want it to also install angular alongside itself in bower as I use a mix of bower and npm.

Nobody is going to use this without Angular, the dependency doesnt need to be in the bower file.

I removed this...

  "dependencies": {
    "angular": ">=1.2"
  },

I think it makes sense for ng-lodash to have that properly removed from its bower.json file.

**Comment by varmint09** [comment]
No comment? This seems a valid suggestion.

**Comment by nwhite89** [comment]
To be honest this is quite common when it comes to bower for example if you look at something like [ui-router](https://github.com/angular-ui/ui-router/blob/master/bower.json#L6) they will do something the same it's more to ensure that the version of Angular supported by ng-lodash is downloaded. When wanting to use an Angular version which is not supported this is when you have to force your version of Angular to be a specific one.
