### ISSUE TITLE
excuse my ignorance

### ISSUE THREAD

**Issue by mdelgadov** [rockabox/ng-lodash#17]
but, do I need also to load lodash?

ie:
st "script src="./bower_components/lodash.js" gt st/script gt
script src="./bower_components/angular.js" /script 
script src="./bower_components/ng-lodash.js" /script
?

thanks in advance

**Comment by nwhite89** [comment]
Hi @mdelgadov,

When using ng-lodash there is no need to load in Lo-dash at all (unless your needing it for anything outside of Angular). Ng-Lodash takes care of all of that for you. Simply add in your ``<script src="ng-lodash.js">`` after your normal Angular script tag and everything should work for you, you will need to remember to load it into Angular in the normal manner for loading things like controllers example below hope that helps.

```js
var app = angular.module('yourAwesomeApp', ['ngLodash']);
var YourCtrl = app.controller('yourController', function($scope, lodash) {
  lodash.assign({ 'a': 1 }, { 'b': 2 }, { 'c': 3 });
});
```
