### ISSUE TITLE
NPM compatible

### ISSUE THREAD

**Issue by lee-40square** [rockabox/ng-lodash#23]
Any chance we could get this in NPM (CommonJS) please?

**Comment by nwhite89** [comment]
Hi what's the value of doing this, if your wanting to use lodash in node I suggest using https://github.com/lodash/lodash-node

**Comment by lee-40square** [comment]
All my dependency management is via NPM instead of Bower. Since we're building in Angular, ng-lodash seemed like the right choice, but it means that we need to start using Bower now. I'll check out lodash-node, but I'm not sure it's as good of a fit for Angular.

**Comment by lee-40square** [comment]
Actually, I guess it really doesn't change much so disregard.

Cheers.

**Comment by nwhite89** [comment]
Ok feel free to reopen if you find you need this cheers @lee-40square
