### ISSUE TITLE
Please update to v4.0.1

### ISSUE THREAD

**Issue by Skyback** [rockabox/ng-lodash#31]
I'm using ng-lodash on my project so I can use lodash "the Angular way". But I really needed some new features of lodash v4.0.1 version. Could you please update it?

**Comment by nwhite89** [comment]
@Skyback there seems to be an issue from what I can see with `lodash-cli` which this project uses in order to generate the lodash files. I have raised an issue and will try and get this sorted ASAP

**Comment by Skyback** [comment]
Thank you very much!

**Comment by nwhite89** [comment]
@Skyback No problem at all it has been on my "To Do" list, it looks like it was a simple thing of not updated docs for `lodash-cli` see release > https://github.com/rockabox/ng-lodash/releases/tag/0.4.0 Cheers :+1:
